# Copyright (c) TigardHighGDC
# SPDX-License-Identifier: Apache-2.0

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests
reviewers: 
  - BrandonPacewic
  - Galaxy25
  
# Keywords that skip the auto assign process
skipKeywords:
  - skip-review
  - no-review
  - revert

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
