# Copyright (c) TigardHighGDC
# SPDX-License-Identifier: Apache-2.0

# Add the following tags to all pr's
do-not-merge:
- '**/*'

waiting-for-review:
- '**/*'

change-sent-to-author:
- '**/*'

# Add automation to all pr's in .github/
automation:
- '.github/**/*'

# Add cmake to all edits to CMakeLists.txt
cmake:
- 'CMakeLists.txt'

# Add md to all edits to markdown files
md:
- '**/*.md'

# Add the core label to all edits in src/
core:
- 'src/**/*'

# Add the toolset label to all edits in tools/
toolset:
- 'tools/**/*'

# Add the test label to all edits in tests/
test:
- 'tests/**/*'